# Generated by Django 5.2.7 on 2026-02-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Village_Dairy', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Cheese', 'Cheese'), ('Fermented', 'Fermented'), ('Fat-based', 'Fat-based'), ('Special', 'Special')], default='Milk', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
