# Generated by Django 5.2.7 on 2026-03-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Village_Dairy', '0004_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
