# Generated by Django 5.2.7 on 2026-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Village_Dairy', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
