# Generated by Django 6.0.2 on 2026-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Village_Dairy', '0017_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
