# Generated by Django 6.0.2 on 2026-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Village_Dairy', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
